version: '3.3'

services:
  web:
    container_name: gc-web
    env_file:
      - .env.local
    build:
      target: production
      context: .
      dockerfile: .docker/web/Dockerfile
    volumes:
      - .:/web:cached
      - node_modules:/web/node_modules
    ports:
      - "3000:3000"
      - "24678:24678"
    tty: true

volumes:
  node_modules: