name: deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: gc-web

jobs:
  deploy:
    name: Push Image to AWS ECR and Deploy to ECS Fargate
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push image to Amazon ECR
        env:
          REPOSITORY_URL: ${{ secrets.ECR_REPOSITORY_URL }}
        run: |
          docker-compose -f docker-compose.yml build web
          docker tag gc-web_web:latest $REPOSITORY_URL:$IMAGE_TAG
          docker push $REPOSITORY_URL:$IMAGE_TAG

      - name: Deploy to ECS Fargate
        run: |
          aws ecs update-service --cluster gc-web --service gc-web --force-new-deployment
